"""add extra audio metadata to mediasset

Revision ID: 4b5d4e1b8ac3
Revises: a4af12a8906b
Create Date: 2025-11-19 17:26:15.588993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b5d4e1b8ac3'
down_revision: Union[str, Sequence[str], None] = 'a4af12a8906b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaasset', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mediaasset', sa.Column('codec', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mediaasset', sa.Column('bit_rate', sa.Integer(), nullable=False))
    op.add_column('mediaasset', sa.Column('frequency', sa.Integer(), nullable=False))
    op.add_column('mediaasset', sa.Column('channels', sa.Integer(), nullable=False))
    op.add_column('mediaasset', sa.Column('channel_layout', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('mediaasset', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaasset', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('mediaasset', 'channel_layout')
    op.drop_column('mediaasset', 'channels')
    op.drop_column('mediaasset', 'frequency')
    op.drop_column('mediaasset', 'bit_rate')
    op.drop_column('mediaasset', 'codec')
    op.drop_column('mediaasset', 'url')
    # ### end Alembic commands ###
