"""add description field to concert

Revision ID: 50e8def3babd
Revises: 8a76acfb37b8
Create Date: 2025-11-09 17:42:31.774445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50e8def3babd'
down_revision: Union[str, Sequence[str], None] = '8a76acfb37b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concert', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concert', 'description')
    # ### end Alembic commands ###
