"""Add popularity to Concert

Revision ID: 8a76acfb37b8
Revises: d3b4944189d2
Create Date: 2025-11-07 18:40:00.281022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a76acfb37b8'
down_revision: Union[str, Sequence[str], None] = 'd3b4944189d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concert', sa.Column('popularity', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concert', 'popularity')
    # ### end Alembic commands ###
