"""Added Artist, Concert, Song tables

Revision ID: a0192cc9fc09
Revises: 2c0f2cc2ea78
Create Date: 2025-11-02 19:49:16.078180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0192cc9fc09'
down_revision: Union[str, Sequence[str], None] = '2c0f2cc2ea78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_artist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_artist', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
