"""add junction table in-between media and concert

Revision ID: a4af12a8906b
Revises: f4a1db08d794
Create Date: 2025-11-19 16:35:01.316977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4af12a8906b'
down_revision: Union[str, Sequence[str], None] = 'f4a1db08d794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediaasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concertsetlistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['mediaasset.id'], ),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concert_id', 'track_number', name='unique_concert_track')
    )
    op.create_index(op.f('ix_concertsetlistitem_track_number'), 'concertsetlistitem', ['track_number'], unique=False)
    op.drop_table('song')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('concert_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], name=op.f('song_concert_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('song_pkey'))
    )
    op.drop_index(op.f('ix_concertsetlistitem_track_number'), table_name='concertsetlistitem')
    op.drop_table('concertsetlistitem')
    op.drop_table('mediaasset')
    # ### end Alembic commands ###
