"""add cover_image_url to concert

Revision ID: acbeb1cca218
Revises: 50e8def3babd
Create Date: 2025-11-13 18:04:38.610818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'acbeb1cca218'
down_revision: Union[str, Sequence[str], None] = '50e8def3babd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concert', sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concert', 'cover_image_url')
    # ### end Alembic commands ###
