"""rename file_path to file_url for concert song

Revision ID: f4a1db08d794
Revises: acbeb1cca218
Create Date: 2025-11-13 18:08:01.585563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4a1db08d794'
down_revision: Union[str, Sequence[str], None] = 'acbeb1cca218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.drop_column('song', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('song', 'file_url')
    # ### end Alembic commands ###
