"""Rearranged user-artist relationship

Revision ID: fea34a4e34b4
Revises: c99d9599796b
Create Date: 2025-11-02 20:22:54.191278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fea34a4e34b4'
down_revision: Union[str, Sequence[str], None] = 'c99d9599796b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artist_user_id_key'), 'artist', type_='unique')
    op.drop_constraint(op.f('artist_user_id_fkey'), 'artist', type_='foreignkey')
    op.drop_column('artist', 'user_id')
    op.add_column('users', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'artist_id')
    op.add_column('artist', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('artist_user_id_fkey'), 'artist', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('artist_user_id_key'), 'artist', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
